### ISSUE TITLE
Page: Building Competence

### ISSUE THREAD

**Issue by betrcode** [crispab/crisp-dna#16]
Write page about “Rocket Days” – how we learn from each other

**Comment by hansbrattberg** [comment]
Rocket Days has been renamed a long time ago to just be RD.
The reason was that Rocket was a little to close to weapon, and that RD
could be interpret as Research and Development.
So I sugest we just name it RD.

**Comment by hkniberg** [comment]
Renamed the page to "Building competence" and will refer to RD and hack-summit and other stuff.

**Comment by hkniberg** [comment]
done
