### ISSUE TITLE
Page: Contracts

### ISSUE THREAD

**Issue by betrcode** [crispab/crisp-dna#26]
Write and publish swedish original and english translations of team contract and shareholder contract.

See: http://dna.crisp.se/docs/contracts.html

**Comment by hkniberg** [comment]
Transcribed the Swedish contracts (copy-paste from .doc to .textile was simple!). 
Will leave the english contracts to someone else (inside or outside Crisp) who is interested enough to want to put energy into it. Put a google translate link for now.
