### ISSUE TITLE
Feedback from Jimmy

### ISSUE THREAD

**Issue by betrcode** [crispab/crisp-dna#3]
Rödmarkerat i bilderna tycker jag är viktigt att korrigera. Grönt är förslag.

![2015-01-21 19 05 53](https://cloud.githubusercontent.com/assets/777108/5843403/b139fe8c-a1ac-11e4-9676-0c59b346375e.png)
![2015-01-21 19 12 59](https://cloud.githubusercontent.com/assets/777108/5843405/b13c1b72-a1ac-11e4-9750-fb269ac25dd5.png)
![2015-01-21 19 14 39](https://cloud.githubusercontent.com/assets/777108/5843402/b1373c88-a1ac-11e4-80e0-d8fc792a1b42.png)
![2015-01-21 19 34 48](https://cloud.githubusercontent.com/assets/777108/5843404/b13acb1e-a1ac-11e4-9799-a1d5985401c4.png)
![screenshots_2015-01-21-18-50-05](https://cloud.githubusercontent.com/assets/777108/5843406/b13c7162-a1ac-11e4-9008-7d645f9ec2ef.png)

**Comment by hansbrattberg** [comment]
Gillar dina gröna förslag, kör (tycker jag)!
/Hasse

**Comment by betrcode** [comment]
Jag kör. :+1:

**Comment by betrcode** [comment]
Fixed everything except the adjustment on the picture: http://dna.crisp.se/assets/WhyItWorks.png

@hkniberg Do you have the original?

**Comment by betrcode** [comment]
@jjanlen Please review the fixes so far. They are live.

**Comment by jjanlen** [comment]
Allt ser bra ut :-)
Förutom att "subcontractors" är kvar i bilden.

**Comment by betrcode** [comment]
@jjanlen Fixed the Why it works picture. No more subcontractors!
