### ISSUE TITLE
Add favicon.ico to site

### ISSUE THREAD

**Issue by ollehallin** [crispab/crisp-dna#30]
And /robots.txt allowing crawlers to crawl everything.

**Comment by betrcode** [comment]
+1 on favicon.
Isn't robots.txt mostly for suggesting that some things shouldn't be crawled?

**Comment by ollehallin** [comment]
Well, having a robots.txt allowing everything is considered a best practice, even if it is unnecessary.

**Comment by betrcode** [comment]
OK! Well, go ahead :-)

**Comment by betrcode** [comment]
Favicon added. 
robots.txt remains

**Comment by ollehallin** [comment]
robots.txt is not needed. Closing issue.
