### ISSUE TITLE
Bullprotokollet vid uppdrag

### ISSUE THREAD

**Issue by jgrape** [crispab/crisp-dna#32]
http://dna.crisp.se/docs/bun-protocol.html

Jag tycker inte det framgår att vi (i alla fall förr) haft en praxis vad gäller bullar för uppdrag (kurs, föredrag, konsultuppdrag) som går ut på att den som tagit bullen inte automatiskt får uppdrage om det blir något.

Istället agerar bullägaren kontaktyta mot kunden och alla som är intresserade hör av sig till bullägaren som tillsammans med kunden (eller låter kunden göra det själv) kommer fram till vem som är lämpligast för kunden.

Det kanske inte funkar så längre?

Jag tyckte i alla fall att det var en bra praxis eftersom man då undviker huggsexa och att kundens behov inte kommer i andra hand.

**Comment by hkniberg** [comment]
Den praxis gäller fortfarande. Ska försöka förtydliga det i dokumentet. Lablar om det till en bug :)

**Comment by hkniberg** [comment]
Jag har förtydligat detta nu.
