### ISSUE TITLE
En sökfunktion vore bra

### ISSUE THREAD

**Issue by jgrape** [crispab/crisp-dna#33]
Det är rätt mycket material och en sökruta vore användbar. Vet inte om GitHub pages har något specifict stöd för sök.

**Comment by betrcode** [comment]
Det finns en Jekyll plugin som löser detta: https://github.com/PascalW/jekyll_indextank

Den finns om omnämnd hör: http://jekyllrb.com/docs/plugins/

**Comment by betrcode** [comment]
Closing because no one is doing it. 😃 Can be reopened ofc.
