### ISSUE TITLE
Byta ut bilderna på handsignlarerna

### ISSUE THREAD

**Issue by jjanlen** [crispab/crisp-dna#34]
Föreslår att bilderna på handsignalerna byts ut mot de som numera finns i:
https://www.dropbox.com/s/f09wokvahfxb9q5/POSTERS%20-%20Handsignaler.pptx?dl=0

**Comment by betrcode** [comment]
Bra idé. Finns de utanför en pptx också?
Den 2 feb 2015 17:02 skrev "jjanlen" notifications@github.com:

**Comment by betrcode** [comment]
@jjanlen Jag har inte MS Office och LibreOffice tolkar inte den där filen rätt... Kan du skapa en PNG bild för varje sida tack?

**Comment by betrcode** [comment]
Blog post about hand signals. Perhaps I can find a better source there.
http://blog.crisp.se/2015/05/06/jimmyjanlen/download-crisps-voting-and-hand-signal-posters
