### ISSUE TITLE
Easier updates of Happiness Index history in the spreadsheet

### ISSUE THREAD

**Issue by radekmika** [crispab/crisp-dna#35]
Hi,

first of all - thanks very much for open-sourcing the Crisp DNA! Very cool, very inspiring...

At Socialbakers, we've decided to give a try to the Happiness Index at first. We are pretty much using the default template. I just made a small script in the Google Docs spreadsheet to update the average history by clicking on a button, instead of having to copy & paste it to another sheet manually. It looks like this: http://cl.ly/image/1e0y152E0F06. Really small and stupid thing, but let me know if you would like to try it & may be incorporate to your template.

**Comment by betrcode** [comment]
Not stupid at all! Will check it out.
Den 8 feb 2015 22:08 skrev "Radek Míka" notifications@github.com:

**Comment by radekmika** [comment]
Hi Max,

[here is](https://docs.google.com/a/socialbakers.com/spreadsheet/ccc?key=0AmiAW9JnXhlZdHhZVDQ3YXBpMGFjcnVjN21fVXBxSEE&usp=sharing) the modified version, you should be able to edit it. If you want to copy it, just follow these steps:
1) Name range "B10:E10" as "averageIndex"
2) Insert [this script](https://gist.github.com/radekmika/6c892b4bf2ff022c982b) 
3) Insert the table for message and button; and insert the button as a drawing 
4) Assign the script to the drawing 
- http://cl.ly/image/1Z3R132D1q2W 
- http://cl.ly/image/3x2j0W331F03

& enjoy! :)

**Comment by hkniberg** [comment]
Thanks for sharing! Tested it. Cool! I'm normally all for automation, but in this case I prefer not to use it. I like the fact that copying the numbers manually forces us to actually look at the history sheet, which increases the likelihood that we will reflect on it and spot patterns. Also, copying the numbers manually takes just a few seconds so I'd prefer to keep the spreadsheet as simple as possible. Thanks anyway though!  (if anyone else at Crisp disagrees, feel free to stick it in).

**Comment by radekmika** [comment]
Ok Henrik, makes perfect sense.
