### ISSUE TITLE
consensus

### ISSUE THREAD

**Issue by pra** [crispab/crisp-dna#4]
Något intresse av att lägga in/integrera: http://blog.crisp.se/2014/03/27/peterantman/crisp-consensus-model-2-1?

//Peter

**Comment by smamol** [comment]
Just a "side" comment: From someone who has forked the model I'd love to have it be part of Crip's DNA and pull it ...

**Comment by hkniberg** [comment]
Good idea! We have a page on decision making and one on hand signals, will check where this can fit in.

**Comment by hkniberg** [comment]
this is now covered in Decisions and Hand Signals.
