### ISSUE TITLE
Experience with this business model in Germany?

### ISSUE THREAD

**Issue by sebastianbachmann** [crispab/crisp-dna#46]
Hi,

Thanks for sharing this! This is really interesting to me.

Do you have experience whether this model also works or could work in Germany? Are you aware of a company in Germany, which adopted this business model?

**Comment by betrcode** [comment]
@sebastianbachmann Glad you find it interesting!

Personally, I don't have any answers to your questions, but I will see if any of my colleagues do.

**Comment by sebastianbachmann** [comment]
Hi,

did any of your colleagues have information?

**Comment by betrcode** [comment]
@sebastianbachmann Sorry, no.

**Comment by sebastianbachmann** [comment]
Ok, thanks @betrcode
