### ISSUE TITLE
question

### ISSUE THREAD

**Issue by hhentschke** [crispab/crisp-dna#49]
Hi there,
my name is Harald Hentschke, I'm part of a loosely organized group of freelancing Data Scientists who are disillusioned with recruiting in its present-day form and who dream of a better way of matching individuals/teams with jobs. We are currently discussing the DNA of a future service/platform for us that would enable us to acquire contracts and work in teams, among other things, and in the process of doing some research found crisp.
Would anyone of you be willing to join us one of these days in a friendly remote session and give us some first-hand experience of crisp? Yes, we will do our homework and read all about crips so we can ask specific questions and won't steal too much of your time. Any other form of insight would of course also be very much appreciated.

Best regards,

Harald Hentschke
Berlin, Germany
https://www.linkedin.com/in/hhentschke/

**Comment by betrcode** [comment]
Harald, I am sorry this was not answered here. Did you get a response elsewhere?

**Comment by betrcode** [comment]
@hhentschke Hello again. Feel free to join https://crispdna.slack.com/ so we can have a discussion there! Closing this issue.
